use pytest to run unit test
```sh
$ python3 test/test_conv_shapetracker.py
Traceback (most recent call last):
  File "/root/tinygrad/test/test_conv_shapetracker.py", line 9, in <module>
    from test.unit.test_shapetracker import shapetracker_getitem
ModuleNotFoundError: No module named 'test.unit'
```

possible fix:
- PYTHONPATH
```sh
$ PYTHONPATH="$PYTHONPATH:$(pwd)" python3 test/test_conv_shapetracker.py

----------------------------------------------------------------------
Ran 2 tests in 1.094s

OK
```

- pytest
```sh
$ python3 -m pytest test/test_conv_shapetracker.py
============================= test session starts =============================
platform linux -- Python 3.10.12, pytest-8.3.3, pluggy-1.5.0
rootdir: /root/tinygrad
plugins: hypothesis-6.116.0, xdist-3.6.1, anyio-4.6.2.post1
collected 2 items

test/test_conv_shapetracker.py ..                                       [100%]

============================== 2 passed in 1.69s ==============================
```

prefer pytest since PYTHONPATH can have side effect

test:
```sh
$ python3 -m pytest test/test_conv_shapetracker.py
============================= test session starts =============================
platform linux -- Python 3.10.12, pytest-8.3.3, pluggy-1.5.0
rootdir: /root/tinygrad
plugins: hypothesis-6.116.0, xdist-3.6.1, anyio-4.6.2.post1
collected 2 items

test/test_conv_shapetracker.py ..                                       [100%]

============================== 2 passed in 1.68s ==============================
```