Add Opt(op=OptOps.LOCAL, axis=6, amt=2) to actions
it's missing if we rebuild all kernels, not just the first 2k.

```
PYTHONPATH="." GPU=1 python3 extra/optimization/get_action_space.py
 29%|█████████████████████████████████████▋                                                                                            | 3682/12701 [01:42<04:11, 35.83it/s]Traceback (most recent call last):
  File "/Users/chenyu/code/tinygrad/extra/optimization/get_action_space.py", line 27, in <module>
    test_rebuild(lin)
  File "/Users/chenyu/code/tinygrad/extra/optimization/get_action_space.py", line 11, in test_rebuild
    assert o in actions, f"{o} is not in actions"
           ^^^^^^^^^^^^
AssertionError: Opt(op=OptOps.LOCAL, axis=6, amt=2) is not in actions
```